spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/imdb-1
    username: root
    password: HrisPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

